### ISSUE TITLE
[programming] all interface

### ISSUE THREAD

**Issue by LauraCoboRuiz** [ShadowOfDragons/AustraNlia#10]

**Comment by ShadowOfDragons** [comment]
Camera limits made and follow player.

The camera doesn't show the outside of the background image and adapts to ALL resolutions.

**Comment by ShadowOfDragons** [comment]
Since Unity is no longer the engine used, this script has become obsolete.

The AGS engine has already it's own system to follow the player without going out of the background when the scenario is bigger than the screen.
