### ISSUE TITLE
Create Pause Screen UI Art

### ISSUE THREAD

**Issue by ShadowOfDragons** [ShadowOfDragons/AustraNlia#14]
We have to create the art and establish the distribution of the UI pause screen, that will follow the already implemented style, futuristic hologram with mechanical buttons.

### Art:
* [x] Tab distribution
* [x] Interface style

**EXPECTED RESULT:**

*An archive png based only with art, that won't be functional but will be ready to be implemented in game.
Name archive:* mockup_gameplay_pause.png

![Pause](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/Mockups/mockup_gameplay_pause.png)

**Comment by ShadowOfDragons** [comment]
Split programming to issue #26

**Comment by ShadowOfDragons** [comment]
Need to reference the resulting images.

**Comment by LauraCoboRuiz** [comment]
Commited in: f5648b6
