### ISSUE TITLE
Create Art Presentation For Display

### ISSUE THREAD

**Issue by ShadowOfDragons** [ShadowOfDragons/AustraNlia#22]
Create presentation art to the final concepts, that will be a version of the concept arts of the characters, environments, thumnails, size charts and mockups.

### Characters: background with logo + new characters
- [x] Chad
- [x] Íca
- [x] Mierins
- [x] Gaedhbaal

### Environments: add logo
- [x] Mierins' office
- [x] Bubble forest

***

### Thumbnails: Total = 12 per thing
- [x] Characters
- [x] Props

***

### Size charts
- [x] Characters
- [x] Props

***

### Mockups
- [x] Title screen
- [x] Ending screen

**EXPECTED RESULT:**

*Multiple final art files in .png for Wiki with their proper name.
Name of archives:* character_01_presentation.png, concept_environment_01.png, character_thumbnails.png, props_thumbnails.png, characters_size_chart.png, props_size_chart.png, mockup_title_screen.png, mockup_ending_screen.png

![Chad](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/WikiResources/character_01_presentation.png)
9a00c5d

![Ica](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/WikiResources/character_02_presentation.png)
77dc232

![Gaedhbaal](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/WikiResources/character_03_presentation.png)
d6f2a01

![Mierins](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/WikiResources/character_04_presentation.png)
d6f2a01

![Mierins' office](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/ConceptArt/Environment/concept_environment_01.png)
0993d91

![Characters Thumbnails](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/ConceptArt/Characters/character_thumbnails.png)
fbf5262

![PropsThumbnails](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/ConceptArt/Props/props_thumbnails.png)
0c15ddf

![Characters Size charts](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/ConceptArt/Characters/characters_size_chart.png)
32dae87

![Props Size charts](https://raw.githubusercontent.com/ShadowOfDragons/AustraNlia/master/ConceptArt/Props/props_size_chart.png)
19d2104

**Comment by ShadowOfDragons** [comment]
[character_01_presentation.png](https://github.com/ShadowOfDragons/AustraNlia/blob/master/WikiResources/character_01_presentation.png)

**Comment by Blannaze** [comment]
Everything is presentable now
