### ISSUE TITLE
Create Animation for the Logo Screen

### ISSUE THREAD

**Issue by LauraCoboRuiz** [ShadowOfDragons/AustraNlia#29]
Create the final animation of the logo. This Logo Screen will be implemented before the Gameplay Screen.

* [x] Animation

**EXPECTED RESULT:**

*We expect to get the final art that the letter they look like wood in the words "Totem" and "Tree". The animation will be something simple but attractive, "Totem" will appear in vertical, while "Tree" will appear from the word "Totem" in horizontal using the second "T" as start.
Name of archive of logo art:* concept_logo_screen_01.png

**Comment by ShadowOfDragons** [comment]
Animation done in commit b149aae
